# Generated by Django 5.0.2 on 2024-03-08 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gasbottle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gasbottle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gasbottle',
            name='user',
        ),
        migrations.CreateModel(
            name='AgencyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('appovel', models.BooleanField(default=False)),
                ('Gas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Booking.gascylinder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GasCategory',
        ),
        migrations.DeleteModel(
            name='GasBottle',
        ),
    ]
